micronaut:
  server:
    cors:
      enabled: true
      configurations:
        all:
          allowedOrigins:
            - http://localhost:3000

akhq:
  connections:
    local:
      properties:
        bootstrap.servers: "kafka:9092"

